# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'hw01.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
from cvApp import cvApp
from PyQt5 import QtCore, QtGui, QtWidgets


class cvMainWindow(object):
    def __init__(self):
        self.app = cvApp()

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(709, 355)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(390, 20, 231, 71))
        self.groupBox_3.setObjectName("groupBox_3")
        self.AugmentedReality = QtWidgets.QPushButton(self.groupBox_3)
        self.AugmentedReality.setGeometry(QtCore.QRect(20, 30, 201, 32))
        self.AugmentedReality.setIconSize(QtCore.QSize(32, 16))
        self.AugmentedReality.setObjectName("AugmentedReality")
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(390, 90, 231, 71))
        self.groupBox_4.setObjectName("groupBox_4")
        self.StereoDisparityMap = QtWidgets.QPushButton(self.groupBox_4)
        self.StereoDisparityMap.setGeometry(QtCore.QRect(20, 30, 201, 32))
        self.StereoDisparityMap.setIconSize(QtCore.QSize(32, 16))
        self.StereoDisparityMap.setObjectName("StereoDisparityMap")
        self.groupBox_5 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_5.setGeometry(QtCore.QRect(390, 160, 231, 101))
        self.groupBox_5.setObjectName("groupBox_5")
        self.KeyPoints = QtWidgets.QPushButton(self.groupBox_5)
        self.KeyPoints.setGeometry(QtCore.QRect(20, 30, 201, 32))
        self.KeyPoints.setIconSize(QtCore.QSize(32, 16))
        self.KeyPoints.setObjectName("KeyPoints")
        self.MatchKeyPoints = QtWidgets.QPushButton(self.groupBox_5)
        self.MatchKeyPoints.setGeometry(QtCore.QRect(20, 60, 201, 32))
        self.MatchKeyPoints.setIconSize(QtCore.QSize(32, 16))
        self.MatchKeyPoints.setObjectName("MatchKeyPoints")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(20, 20, 351, 241))
        self.groupBox.setObjectName("groupBox")
        self.FindCorners = QtWidgets.QPushButton(self.groupBox)
        self.FindCorners.setGeometry(QtCore.QRect(20, 40, 141, 32))
        self.FindCorners.setIconSize(QtCore.QSize(32, 16))
        self.FindCorners.setObjectName("FindCorners")
        self.FindIntrinsic = QtWidgets.QPushButton(self.groupBox)
        self.FindIntrinsic.setGeometry(QtCore.QRect(20, 110, 141, 32))
        self.FindIntrinsic.setIconSize(QtCore.QSize(32, 16))
        self.FindIntrinsic.setObjectName("FindIntrinsic")
        self.FindDistortion = QtWidgets.QPushButton(self.groupBox)
        self.FindDistortion.setGeometry(QtCore.QRect(20, 170, 141, 32))
        self.FindDistortion.setIconSize(QtCore.QSize(32, 16))
        self.FindDistortion.setObjectName("FindDistortion")
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_2.setGeometry(QtCore.QRect(180, 30, 151, 191))
        self.groupBox_2.setObjectName("groupBox_2")
        self.FindExtrinsic = QtWidgets.QPushButton(self.groupBox_2)
        self.FindExtrinsic.setGeometry(QtCore.QRect(10, 140, 131, 32))
        self.FindExtrinsic.setIconSize(QtCore.QSize(32, 16))
        self.FindExtrinsic.setObjectName("FindExtrinsic")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setGeometry(QtCore.QRect(30, 40, 101, 16))
        self.label.setObjectName("label")
        self.FileList = QtWidgets.QComboBox(self.groupBox_2)
        self.FileList.setGeometry(QtCore.QRect(20, 80, 111, 26))
        self.FileList.setObjectName("FileList")
        self.FileList.addItem("")
        self.FileList.addItem("")
        self.FileList.addItem("")
        self.FileList.addItem("")
        self.FileList.addItem("")
        self.FileList.addItem("")
        self.FileList.addItem("")
        self.FileList.addItem("")
        self.FileList.addItem("")
        self.FileList.addItem("")
        self.FileList.addItem("")
        self.FileList.addItem("")
        self.FileList.addItem("")
        self.FileList.addItem("")
        self.FileList.addItem("")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(380, 290, 321, 16))
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 709, 22))
        self.menubar.setObjectName("menubar")
        self.menu2020_cvdl_hw01 = QtWidgets.QMenu(self.menubar)
        self.menu2020_cvdl_hw01.setObjectName("menu2020_cvdl_hw01")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menu2020_cvdl_hw01.menuAction())

        self.retranslateUi(MainWindow)
        self.FindCorners.clicked.connect(self.app.find_corner)
        self.FindIntrinsic.clicked.connect(self.app.find_intrinsic)
        self.FindDistortion.clicked.connect(self.app.find_distortion)
        self.FileList.activated['int'].connect(self.app.set_file_idx)
        self.FindExtrinsic.clicked.connect(self.app.find_extrinsic)
        self.AugmentedReality.clicked.connect(self.app.ar_draw_shape)
        self.StereoDisparityMap.clicked.connect(self.app.find_disparity_map)
        self.KeyPoints.clicked.connect(self.app.find_keypoints)
        self.MatchKeyPoints.clicked.connect(self.app.match_keypoints)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_3.setTitle(_translate(
            "MainWindow", "2. Augmented Reality"))
        self.AugmentedReality.setText(_translate(
            "MainWindow", "2.1 Augmented Reality"))
        self.groupBox_4.setTitle(_translate(
            "MainWindow", "3. Stereo Disparity Map"))
        self.StereoDisparityMap.setText(_translate(
            "MainWindow", "3.1 Stereo Disparity Map"))
        self.groupBox_5.setTitle(_translate("MainWindow", "4. SIFT"))
        self.KeyPoints.setText(_translate("MainWindow", "4.1 Keypoints"))
        self.MatchKeyPoints.setText(_translate(
            "MainWindow", "4.2 Matched Keypoints"))
        self.groupBox.setTitle(_translate("MainWindow", "1. Calibration"))
        self.FindCorners.setText(_translate("MainWindow", "1.1 Find Corners"))
        self.FindIntrinsic.setText(_translate(
            "MainWindow", "1.2 Find Intrinsic"))
        self.FindDistortion.setText(_translate(
            "MainWindow", "1.4 Find Distortion"))
        self.groupBox_2.setTitle(_translate(
            "MainWindow", "1.3 Find Extrinsic"))
        self.FindExtrinsic.setText(_translate(
            "MainWindow", "1.3 Find Extrinsic"))
        self.label.setText(_translate("MainWindow", "Select Image"))
        self.FileList.setItemText(0, _translate("MainWindow", "1"))
        self.FileList.setItemText(1, _translate("MainWindow", "2"))
        self.FileList.setItemText(2, _translate("MainWindow", "3"))
        self.FileList.setItemText(3, _translate("MainWindow", "4"))
        self.FileList.setItemText(4, _translate("MainWindow", "5"))
        self.FileList.setItemText(5, _translate("MainWindow", "6"))
        self.FileList.setItemText(6, _translate("MainWindow", "7"))
        self.FileList.setItemText(7, _translate("MainWindow", "8"))
        self.FileList.setItemText(8, _translate("MainWindow", "9"))
        self.FileList.setItemText(9, _translate("MainWindow", "10"))
        self.FileList.setItemText(10, _translate("MainWindow", "11"))
        self.FileList.setItemText(11, _translate("MainWindow", "12"))
        self.FileList.setItemText(12, _translate("MainWindow", "13"))
        self.FileList.setItemText(13, _translate("MainWindow", "14"))
        self.FileList.setItemText(14, _translate("MainWindow", "15"))
        self.label_2.setText(_translate(
            "MainWindow", "Name: Cheng Wei (P76091226) CVDL2020 HW01"))
        self.menu2020_cvdl_hw01.setTitle(
            _translate("MainWindow", "2020 cvdl hw01"))


if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = cvMainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
