# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'hw01.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
from cvApp import cvApp
from pcaApp import pcaApp
from PyQt5 import QtCore, QtGui, QtWidgets


class appMainWindow(object):
    def __init__(self):
        self.cvApp = cvApp()
        self.pcaApp = pcaApp()

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(483, 369)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(210, 20, 231, 91))
        self.groupBox_3.setObjectName("groupBox_3")
        self.PerspectiveTransform = QtWidgets.QPushButton(self.groupBox_3)
        self.PerspectiveTransform.setGeometry(QtCore.QRect(20, 30, 201, 32))
        self.PerspectiveTransform.setIconSize(QtCore.QSize(32, 16))
        self.PerspectiveTransform.setObjectName("PerspectiveTransform")
        self.groupBox_5 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_5.setGeometry(QtCore.QRect(210, 120, 231, 131))
        self.groupBox_5.setObjectName("groupBox_5")
        self.ImgReconstruction = QtWidgets.QPushButton(self.groupBox_5)
        self.ImgReconstruction.setGeometry(QtCore.QRect(10, 40, 201, 32))
        self.ImgReconstruction.setIconSize(QtCore.QSize(32, 16))
        self.ImgReconstruction.setObjectName("ImgReconstruction")
        self.ReconstructionError = QtWidgets.QPushButton(self.groupBox_5)
        self.ReconstructionError.setGeometry(QtCore.QRect(10, 80, 201, 32))
        self.ReconstructionError.setIconSize(QtCore.QSize(32, 16))
        self.ReconstructionError.setObjectName("ReconstructionError")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(20, 20, 171, 91))
        self.groupBox.setObjectName("groupBox")
        self.BgSubtraction = QtWidgets.QPushButton(self.groupBox)
        self.BgSubtraction.setGeometry(QtCore.QRect(10, 40, 151, 32))
        self.BgSubtraction.setIconSize(QtCore.QSize(32, 16))
        self.BgSubtraction.setObjectName("BgSubtraction")
        self.NameLabel = QtWidgets.QLabel(self.centralwidget)
        self.NameLabel.setGeometry(QtCore.QRect(130, 270, 321, 16))
        self.NameLabel.setObjectName("NameLabel")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 120, 171, 131))
        self.groupBox_2.setObjectName("groupBox_2")
        self.Preprocessing = QtWidgets.QPushButton(self.groupBox_2)
        self.Preprocessing.setGeometry(QtCore.QRect(10, 40, 151, 32))
        self.Preprocessing.setIconSize(QtCore.QSize(32, 16))
        self.Preprocessing.setObjectName("Preprocessing")
        self.VideoTracking = QtWidgets.QPushButton(self.groupBox_2)
        self.VideoTracking.setGeometry(QtCore.QRect(10, 80, 151, 32))
        self.VideoTracking.setIconSize(QtCore.QSize(32, 16))
        self.VideoTracking.setObjectName("VideoTracking")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 483, 24))
        self.menubar.setObjectName("menubar")
        self.menu2020_cvdl_hw02 = QtWidgets.QMenu(self.menubar)
        self.menu2020_cvdl_hw02.setObjectName("menu2020_cvdl_hw02")
        MainWindow.setMenuBar(self.menubar)
        self.statusbae = QtWidgets.QStatusBar(MainWindow)
        self.statusbae.setObjectName("statusbae")
        MainWindow.setStatusBar(self.statusbae)
        self.menubar.addAction(self.menu2020_cvdl_hw02.menuAction())

        self.retranslateUi(MainWindow)
        self.BgSubtraction.clicked.connect(self.cvApp.bg_subtraction)
        self.Preprocessing.clicked.connect(self.cvApp.preprocessing)
        self.VideoTracking.clicked.connect(self.cvApp.video_tracking)
        self.PerspectiveTransform.clicked.connect(self.cvApp.prespective_trans)
        self.ImgReconstruction.clicked.connect(self.pcaApp.img_reconstruct)
        self.ReconstructionError.clicked.connect(self.pcaApp.recon_error)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_3.setTitle(_translate(
            "MainWindow", "3. Perspective Transform"))
        self.PerspectiveTransform.setText(_translate(
            "MainWindow", "3.1 Perspective Transform"))
        self.groupBox_5.setTitle(_translate("MainWindow", "4. PCA"))
        self.ImgReconstruction.setText(_translate(
            "MainWindow", "4.1 Img Recontruction"))
        self.ReconstructionError.setText(_translate(
            "MainWindow", "4.2 Reconstruction Error"))
        self.groupBox.setTitle(_translate(
            "MainWindow", "1. Background Subtraction"))
        self.BgSubtraction.setText(_translate(
            "MainWindow", "1.1 Bg subtraction"))
        self.NameLabel.setText(_translate(
            "MainWindow", "Name: Cheng Wei (P76091226) CVDL2020 HW02"))
        self.groupBox_2.setTitle(_translate("MainWindow", "2. Optical Flow"))
        self.Preprocessing.setText(_translate(
            "MainWindow", "2.1 Preprocessing"))
        self.VideoTracking.setText(_translate(
            "MainWindow", "2.2 Video tracking"))
        self.menu2020_cvdl_hw02.setTitle(
            _translate("MainWindow", "2020 cvdl hw01"))


if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = appMainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
