# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'vgg.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
from resNetApp import resNetApp
from PyQt5.QtCore import Qt
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QIntValidator, QFont


class resnetMainWindow(object):
    def __init__(self):
        self.app = resNetApp()

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(257, 385)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 280, 211, 51))
        self.label_2.setObjectName("label_2")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(20, 20, 211, 251))
        self.groupBox.setObjectName("groupBox")
        self.showProgress = QtWidgets.QPushButton(self.groupBox)
        self.showProgress.setGeometry(QtCore.QRect(10, 30, 191, 32))
        self.showProgress.setObjectName("showProgress")
        self.showScreenshot = QtWidgets.QPushButton(self.groupBox)
        self.showScreenshot.setGeometry(QtCore.QRect(10, 70, 191, 32))
        self.showScreenshot.setObjectName("showScreenshot")
        self.inference = QtWidgets.QPushButton(self.groupBox)
        self.inference.setGeometry(QtCore.QRect(50, 210, 113, 32))
        self.inference.setObjectName("inference")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 257, 24))
        self.menubar.setObjectName("menubar")
        self.menucvdl2020_hw02 = QtWidgets.QMenu(self.menubar)
        self.menucvdl2020_hw02.setObjectName("menucvdl2020_hw02")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menucvdl2020_hw02.menuAction())

        self.retranslateUi(MainWindow)
        self.inference.clicked.connect(self.app.inference)
        self.showProgress.clicked.connect(self.app.show_progress)
        self.showScreenshot.clicked.connect(self.app.show_progress)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Name: Cheng Wei (P76091226) \n"
                                        "CVDL2020 HW02"))
        self.groupBox.setTitle(_translate("MainWindow", "ResNet50"))
        self.showProgress.setText(_translate("MainWindow", "Show Progress"))
        self.showScreenshot.setText(
            _translate("MainWindow", "Show Screenshot"))
        self.inference.setText(_translate("MainWindow", "Ramdom Test"))
        self.menucvdl2020_hw02.setTitle(
            _translate("MainWindow", "cvdl202 hw02"))


if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = resnetMainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
